### ISSUE TITLE
Installation help

### ISSUE THREAD

**Issue by vihjepaikka** [xchwarze/SMF2WPBridge#1]
How I can install this bridge? Seems that it's not smf modification package via package manager.
Post your email so I will request a private project with good fee:)

**Comment by xchwarze** [comment]
for install from github:
1) Download from button "Download ZIP"
2) Uncompress zip
3) Zip the content of "SMF2WPBridge-master" folder to a new zip
4) Upload via package manager

Email me to xchwarze@gmail.com
