### ISSUE TITLE
When installed cant logout on SMF

### ISSUE THREAD

**Issue by ViewFromTheBoundary** [xchwarze/SMF2WPBridge#2]
When the package is installed I am unable to log out from SMF, it just creates a whitescreen, do you have any idea why?

**Comment by djeepee** [comment]
I have install this package on smf2 and now when I want to login with my admin account nothing is displayed!!! Just a withescreen!!! What is this mod? Have you ever had this issue? I  can't used anymore my forum and I'm blocked by this. How can I do????
